name: Automated tests

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright and dependencies
        run: python -m playwright install chromium --with-deps

      - name: Run tests with credentials
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          LOCKED_USER_LOGIN: ${{ secrets.LOCKED_USER_LOGIN }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: pytest --alluredir=allure_results

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure_results
          path:
            allure_results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && sudo tar -zxvf allure-2.32.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - run: allure generate -c allure_results -o _site

      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: [test, generate-report]
    name: Report publication

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
