name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: install dependencies for Playwright
        run: sudo apt-get install -y libnss3 libgconf-2-4 libxss1 libasound2
      - name: Clear Playwright cache
        run: rm -rf ~/.cache/ms-playwright
      - name: Install Playwright Chromium
        run: npx playwright install
      - name: Run a script
        env:
          MY_SECRET: ${{ secrets.BASE_URL }}
        run: |
          echo "Using my secret: $BASE_URL"
      - name: Run test
        run: pytest
